#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ReceiptRewards.Droid2.Resource", IsApplication=true)]

namespace ReceiptRewards.Droid2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			LegacyBar.Library.Resource.Attribute.background = ReceiptRewards.Droid2.Resource.Attribute.background;
			LegacyBar.Library.Resource.Attribute.background_item = ReceiptRewards.Droid2.Resource.Attribute.background_item;
			LegacyBar.Library.Resource.Attribute.is_bottom = ReceiptRewards.Droid2.Resource.Attribute.is_bottom;
			LegacyBar.Library.Resource.Attribute.light_icons = ReceiptRewards.Droid2.Resource.Attribute.light_icons;
			LegacyBar.Library.Resource.Attribute.separator = ReceiptRewards.Droid2.Resource.Attribute.separator;
			LegacyBar.Library.Resource.Attribute.theme = ReceiptRewards.Droid2.Resource.Attribute.theme;
			LegacyBar.Library.Resource.Attribute.title = ReceiptRewards.Droid2.Resource.Attribute.title;
			LegacyBar.Library.Resource.Attribute.title_color = ReceiptRewards.Droid2.Resource.Attribute.title_color;
			LegacyBar.Library.Resource.Color.Red = ReceiptRewards.Droid2.Resource.Color.Red;
			LegacyBar.Library.Resource.Color.actionbar_accentcolor_black = ReceiptRewards.Droid2.Resource.Color.actionbar_accentcolor_black;
			LegacyBar.Library.Resource.Color.actionbar_accentcolor_blue = ReceiptRewards.Droid2.Resource.Color.actionbar_accentcolor_blue;
			LegacyBar.Library.Resource.Color.actionbar_accentcolor_darkgray = ReceiptRewards.Droid2.Resource.Color.actionbar_accentcolor_darkgray;
			LegacyBar.Library.Resource.Color.actionbar_accentcolor_lightgray = ReceiptRewards.Droid2.Resource.Color.actionbar_accentcolor_lightgray;
			LegacyBar.Library.Resource.Color.actionbar_background_end = ReceiptRewards.Droid2.Resource.Color.actionbar_background_end;
			LegacyBar.Library.Resource.Color.actionbar_background_end_alt = ReceiptRewards.Droid2.Resource.Color.actionbar_background_end_alt;
			LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end = ReceiptRewards.Droid2.Resource.Color.actionbar_background_item_pressed_end;
			LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end_alt = ReceiptRewards.Droid2.Resource.Color.actionbar_background_item_pressed_end_alt;
			LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start = ReceiptRewards.Droid2.Resource.Color.actionbar_background_item_pressed_start;
			LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start_alt = ReceiptRewards.Droid2.Resource.Color.actionbar_background_item_pressed_start_alt;
			LegacyBar.Library.Resource.Color.actionbar_background_start = ReceiptRewards.Droid2.Resource.Color.actionbar_background_start;
			LegacyBar.Library.Resource.Color.actionbar_background_start_alt = ReceiptRewards.Droid2.Resource.Color.actionbar_background_start_alt;
			LegacyBar.Library.Resource.Color.actionbar_maincolor_black = ReceiptRewards.Droid2.Resource.Color.actionbar_maincolor_black;
			LegacyBar.Library.Resource.Color.actionbar_maincolor_blue = ReceiptRewards.Droid2.Resource.Color.actionbar_maincolor_blue;
			LegacyBar.Library.Resource.Color.actionbar_maincolor_darkgray = ReceiptRewards.Droid2.Resource.Color.actionbar_maincolor_darkgray;
			LegacyBar.Library.Resource.Color.actionbar_maincolor_lightgray = ReceiptRewards.Droid2.Resource.Color.actionbar_maincolor_lightgray;
			LegacyBar.Library.Resource.Color.actionbar_pressedcolor_black = ReceiptRewards.Droid2.Resource.Color.actionbar_pressedcolor_black;
			LegacyBar.Library.Resource.Color.actionbar_pressedcolor_blue = ReceiptRewards.Droid2.Resource.Color.actionbar_pressedcolor_blue;
			LegacyBar.Library.Resource.Color.actionbar_pressedcolor_darkgray = ReceiptRewards.Droid2.Resource.Color.actionbar_pressedcolor_darkgray;
			LegacyBar.Library.Resource.Color.actionbar_pressedcolor_lightgray = ReceiptRewards.Droid2.Resource.Color.actionbar_pressedcolor_lightgray;
			LegacyBar.Library.Resource.Color.actionbar_separator = ReceiptRewards.Droid2.Resource.Color.actionbar_separator;
			LegacyBar.Library.Resource.Color.actionbar_separator_alt = ReceiptRewards.Droid2.Resource.Color.actionbar_separator_alt;
			LegacyBar.Library.Resource.Color.actionbar_separator_black = ReceiptRewards.Droid2.Resource.Color.actionbar_separator_black;
			LegacyBar.Library.Resource.Color.actionbar_separator_blue = ReceiptRewards.Droid2.Resource.Color.actionbar_separator_blue;
			LegacyBar.Library.Resource.Color.actionbar_separator_darkgray = ReceiptRewards.Droid2.Resource.Color.actionbar_separator_darkgray;
			LegacyBar.Library.Resource.Color.actionbar_separator_lightgray = ReceiptRewards.Droid2.Resource.Color.actionbar_separator_lightgray;
			LegacyBar.Library.Resource.Color.actionbar_title = ReceiptRewards.Droid2.Resource.Color.actionbar_title;
			LegacyBar.Library.Resource.Color.actionbar_title_alt = ReceiptRewards.Droid2.Resource.Color.actionbar_title_alt;
			LegacyBar.Library.Resource.Color.actionbar_title_black = ReceiptRewards.Droid2.Resource.Color.actionbar_title_black;
			LegacyBar.Library.Resource.Color.actionbar_title_blue = ReceiptRewards.Droid2.Resource.Color.actionbar_title_blue;
			LegacyBar.Library.Resource.Color.actionbar_title_darkgray = ReceiptRewards.Droid2.Resource.Color.actionbar_title_darkgray;
			LegacyBar.Library.Resource.Color.actionbar_title_lightgray = ReceiptRewards.Droid2.Resource.Color.actionbar_title_lightgray;
			LegacyBar.Library.Resource.Color.black = ReceiptRewards.Droid2.Resource.Color.black;
			LegacyBar.Library.Resource.Color.blue = ReceiptRewards.Droid2.Resource.Color.blue;
			LegacyBar.Library.Resource.Color.bottomactionbar_background_end = ReceiptRewards.Droid2.Resource.Color.bottomactionbar_background_end;
			LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_end = ReceiptRewards.Droid2.Resource.Color.bottomactionbar_background_item_pressed_end;
			LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_start = ReceiptRewards.Droid2.Resource.Color.bottomactionbar_background_item_pressed_start;
			LegacyBar.Library.Resource.Color.bottomactionbar_background_start = ReceiptRewards.Droid2.Resource.Color.bottomactionbar_background_start;
			LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_black = ReceiptRewards.Droid2.Resource.Color.bottomactionbar_maincolor_black;
			LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_blue = ReceiptRewards.Droid2.Resource.Color.bottomactionbar_maincolor_blue;
			LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_darkgray = ReceiptRewards.Droid2.Resource.Color.bottomactionbar_maincolor_darkgray;
			LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_lightgray = ReceiptRewards.Droid2.Resource.Color.bottomactionbar_maincolor_lightgray;
			LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_black = ReceiptRewards.Droid2.Resource.Color.bottomactionbar_pressedcolor_black;
			LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_blue = ReceiptRewards.Droid2.Resource.Color.bottomactionbar_pressedcolor_blue;
			LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_darkgray = ReceiptRewards.Droid2.Resource.Color.bottomactionbar_pressedcolor_darkgray;
			LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_lightgray = ReceiptRewards.Droid2.Resource.Color.bottomactionbar_pressedcolor_lightgray;
			LegacyBar.Library.Resource.Color.bottomactionbar_separator = ReceiptRewards.Droid2.Resource.Color.bottomactionbar_separator;
			LegacyBar.Library.Resource.Color.bottomactionbar_title = ReceiptRewards.Droid2.Resource.Color.bottomactionbar_title;
			LegacyBar.Library.Resource.Color.green = ReceiptRewards.Droid2.Resource.Color.green;
			LegacyBar.Library.Resource.Color.grey = ReceiptRewards.Droid2.Resource.Color.grey;
			LegacyBar.Library.Resource.Color.pager_black = ReceiptRewards.Droid2.Resource.Color.pager_black;
			LegacyBar.Library.Resource.Color.pager_blue = ReceiptRewards.Droid2.Resource.Color.pager_blue;
			LegacyBar.Library.Resource.Color.pager_darkgray = ReceiptRewards.Droid2.Resource.Color.pager_darkgray;
			LegacyBar.Library.Resource.Color.pager_lightgray = ReceiptRewards.Droid2.Resource.Color.pager_lightgray;
			LegacyBar.Library.Resource.Color.red = ReceiptRewards.Droid2.Resource.Color.red;
			LegacyBar.Library.Resource.Color.white = ReceiptRewards.Droid2.Resource.Color.white;
			LegacyBar.Library.Resource.Color.yellow = ReceiptRewards.Droid2.Resource.Color.yellow;
			LegacyBar.Library.Resource.Dimension.actionbar_accentheight = ReceiptRewards.Droid2.Resource.Dimension.actionbar_accentheight;
			LegacyBar.Library.Resource.Dimension.actionbar_height = ReceiptRewards.Droid2.Resource.Dimension.actionbar_height;
			LegacyBar.Library.Resource.Dimension.actionbar_home_item_width = ReceiptRewards.Droid2.Resource.Dimension.actionbar_home_item_width;
			LegacyBar.Library.Resource.Dimension.actionbar_item_height = ReceiptRewards.Droid2.Resource.Dimension.actionbar_item_height;
			LegacyBar.Library.Resource.Dimension.actionbar_item_height_over = ReceiptRewards.Droid2.Resource.Dimension.actionbar_item_height_over;
			LegacyBar.Library.Resource.Dimension.actionbar_item_height_overflow = ReceiptRewards.Droid2.Resource.Dimension.actionbar_item_height_overflow;
			LegacyBar.Library.Resource.Dimension.actionbar_item_width = ReceiptRewards.Droid2.Resource.Dimension.actionbar_item_width;
			LegacyBar.Library.Resource.Drawable.actionbar_back_indicator = ReceiptRewards.Droid2.Resource.Drawable.actionbar_back_indicator;
			LegacyBar.Library.Resource.Drawable.actionbar_back_indicator_dark = ReceiptRewards.Droid2.Resource.Drawable.actionbar_back_indicator_dark;
			LegacyBar.Library.Resource.Drawable.actionbar_background = ReceiptRewards.Droid2.Resource.Drawable.actionbar_background;
			LegacyBar.Library.Resource.Drawable.actionbar_background_alt = ReceiptRewards.Droid2.Resource.Drawable.actionbar_background_alt;
			LegacyBar.Library.Resource.Drawable.actionbar_background_black = ReceiptRewards.Droid2.Resource.Drawable.actionbar_background_black;
			LegacyBar.Library.Resource.Drawable.actionbar_background_blue = ReceiptRewards.Droid2.Resource.Drawable.actionbar_background_blue;
			LegacyBar.Library.Resource.Drawable.actionbar_background_darkgray = ReceiptRewards.Droid2.Resource.Drawable.actionbar_background_darkgray;
			LegacyBar.Library.Resource.Drawable.actionbar_background_lightgray = ReceiptRewards.Droid2.Resource.Drawable.actionbar_background_lightgray;
			LegacyBar.Library.Resource.Drawable.actionbar_btn = ReceiptRewards.Droid2.Resource.Drawable.actionbar_btn;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_alt = ReceiptRewards.Droid2.Resource.Drawable.actionbar_btn_alt;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_black = ReceiptRewards.Droid2.Resource.Drawable.actionbar_btn_black;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_blue = ReceiptRewards.Droid2.Resource.Drawable.actionbar_btn_blue;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_darkgray = ReceiptRewards.Droid2.Resource.Drawable.actionbar_btn_darkgray;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_lightgray = ReceiptRewards.Droid2.Resource.Drawable.actionbar_btn_lightgray;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_normal = ReceiptRewards.Droid2.Resource.Drawable.actionbar_btn_normal;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_normal_alt = ReceiptRewards.Droid2.Resource.Drawable.actionbar_btn_normal_alt;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed = ReceiptRewards.Droid2.Resource.Drawable.actionbar_btn_pressed;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed_alt = ReceiptRewards.Droid2.Resource.Drawable.actionbar_btn_pressed_alt;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_background = ReceiptRewards.Droid2.Resource.Drawable.bottomactionbar_background;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_background_black = ReceiptRewards.Droid2.Resource.Drawable.bottomactionbar_background_black;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_background_blue = ReceiptRewards.Droid2.Resource.Drawable.bottomactionbar_background_blue;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_background_darkgray = ReceiptRewards.Droid2.Resource.Drawable.bottomactionbar_background_darkgray;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_background_lightgray = ReceiptRewards.Droid2.Resource.Drawable.bottomactionbar_background_lightgray;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn = ReceiptRewards.Droid2.Resource.Drawable.bottomactionbar_btn;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_black = ReceiptRewards.Droid2.Resource.Drawable.bottomactionbar_btn_black;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_blue = ReceiptRewards.Droid2.Resource.Drawable.bottomactionbar_btn_blue;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_darkgray = ReceiptRewards.Droid2.Resource.Drawable.bottomactionbar_btn_darkgray;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_lightgray = ReceiptRewards.Droid2.Resource.Drawable.bottomactionbar_btn_lightgray;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_normal = ReceiptRewards.Droid2.Resource.Drawable.bottomactionbar_btn_normal;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_pressed = ReceiptRewards.Droid2.Resource.Drawable.bottomactionbar_btn_pressed;
			LegacyBar.Library.Resource.Drawable.dropdown_btn_holo_dark = ReceiptRewards.Droid2.Resource.Drawable.dropdown_btn_holo_dark;
			LegacyBar.Library.Resource.Drawable.dropdown_btn_holo_light = ReceiptRewards.Droid2.Resource.Drawable.dropdown_btn_holo_light;
			LegacyBar.Library.Resource.Drawable.dropdown_disabled_holo_dark = ReceiptRewards.Droid2.Resource.Drawable.dropdown_disabled_holo_dark;
			LegacyBar.Library.Resource.Drawable.dropdown_disabled_holo_light = ReceiptRewards.Droid2.Resource.Drawable.dropdown_disabled_holo_light;
			LegacyBar.Library.Resource.Drawable.dropdown_focused_holo_dark = ReceiptRewards.Droid2.Resource.Drawable.dropdown_focused_holo_dark;
			LegacyBar.Library.Resource.Drawable.dropdown_focused_holo_light = ReceiptRewards.Droid2.Resource.Drawable.dropdown_focused_holo_light;
			LegacyBar.Library.Resource.Drawable.dropdown_normal_holo_dark = ReceiptRewards.Droid2.Resource.Drawable.dropdown_normal_holo_dark;
			LegacyBar.Library.Resource.Drawable.dropdown_normal_holo_light = ReceiptRewards.Droid2.Resource.Drawable.dropdown_normal_holo_light;
			LegacyBar.Library.Resource.Drawable.dropdown_pressed_holo_dark = ReceiptRewards.Droid2.Resource.Drawable.dropdown_pressed_holo_dark;
			LegacyBar.Library.Resource.Drawable.dropdown_pressed_holo_light = ReceiptRewards.Droid2.Resource.Drawable.dropdown_pressed_holo_light;
			LegacyBar.Library.Resource.Drawable.ic_action_overflow = ReceiptRewards.Droid2.Resource.Drawable.ic_action_overflow;
			LegacyBar.Library.Resource.Drawable.ic_action_overflow_dark = ReceiptRewards.Droid2.Resource.Drawable.ic_action_overflow_dark;
			LegacyBar.Library.Resource.Id.actionbar_actions = ReceiptRewards.Droid2.Resource.Id.actionbar_actions;
			LegacyBar.Library.Resource.Id.actionbar_home = ReceiptRewards.Droid2.Resource.Id.actionbar_home;
			LegacyBar.Library.Resource.Id.actionbar_home_bg = ReceiptRewards.Droid2.Resource.Id.actionbar_home_bg;
			LegacyBar.Library.Resource.Id.actionbar_home_btn = ReceiptRewards.Droid2.Resource.Id.actionbar_home_btn;
			LegacyBar.Library.Resource.Id.actionbar_home_is_back = ReceiptRewards.Droid2.Resource.Id.actionbar_home_is_back;
			LegacyBar.Library.Resource.Id.actionbar_home_logo = ReceiptRewards.Droid2.Resource.Id.actionbar_home_logo;
			LegacyBar.Library.Resource.Id.actionbar_item = ReceiptRewards.Droid2.Resource.Id.actionbar_item;
			LegacyBar.Library.Resource.Id.actionbar_progress = ReceiptRewards.Droid2.Resource.Id.actionbar_progress;
			LegacyBar.Library.Resource.Id.actionbar_spinner = ReceiptRewards.Droid2.Resource.Id.actionbar_spinner;
			LegacyBar.Library.Resource.Id.actionbar_title = ReceiptRewards.Droid2.Resource.Id.actionbar_title;
			LegacyBar.Library.Resource.Id.actionbar_title_layout = ReceiptRewards.Droid2.Resource.Id.actionbar_title_layout;
			LegacyBar.Library.Resource.Id.custom = ReceiptRewards.Droid2.Resource.Id.custom;
			LegacyBar.Library.Resource.Id.holo_black = ReceiptRewards.Droid2.Resource.Id.holo_black;
			LegacyBar.Library.Resource.Id.holo_blue = ReceiptRewards.Droid2.Resource.Id.holo_blue;
			LegacyBar.Library.Resource.Id.holo_gray = ReceiptRewards.Droid2.Resource.Id.holo_gray;
			LegacyBar.Library.Resource.Id.holo_light = ReceiptRewards.Droid2.Resource.Id.holo_light;
			LegacyBar.Library.Resource.Id.overflow_spinner = ReceiptRewards.Droid2.Resource.Id.overflow_spinner;
			LegacyBar.Library.Resource.Id.screen = ReceiptRewards.Droid2.Resource.Id.screen;
			LegacyBar.Library.Resource.Layout.actionbar = ReceiptRewards.Droid2.Resource.Layout.actionbar;
			LegacyBar.Library.Resource.Layout.actionbar_item = ReceiptRewards.Droid2.Resource.Layout.actionbar_item;
			LegacyBar.Library.Resource.Layout.blankspinner = ReceiptRewards.Droid2.Resource.Layout.blankspinner;
			LegacyBar.Library.Resource.Layout.overflowactionbar_item = ReceiptRewards.Droid2.Resource.Layout.overflowactionbar_item;
			LegacyBar.Library.Resource.Layout.spinneritem = ReceiptRewards.Droid2.Resource.Layout.spinneritem;
			LegacyBar.Library.Resource.String.actionbar_activity_not_found = ReceiptRewards.Droid2.Resource.String.actionbar_activity_not_found;
			LegacyBar.Library.Resource.Style.actionbar = ReceiptRewards.Droid2.Resource.Style.actionbar;
			LegacyBar.Library.Resource.Style.actionbarhomeitem = ReceiptRewards.Droid2.Resource.Style.actionbarhomeitem;
			LegacyBar.Library.Resource.Style.actionbarhomelogo = ReceiptRewards.Droid2.Resource.Style.actionbarhomelogo;
			LegacyBar.Library.Resource.Style.actionbaritem = ReceiptRewards.Droid2.Resource.Style.actionbaritem;
			LegacyBar.Library.Resource.Style.actionbarprogressbar = ReceiptRewards.Droid2.Resource.Style.actionbarprogressbar;
			LegacyBar.Library.Resource.Style.clearbutton = ReceiptRewards.Droid2.Resource.Style.clearbutton;
			LegacyBar.Library.Resource.Styleable.actionbar = ReceiptRewards.Droid2.Resource.Styleable.actionbar;
			LegacyBar.Library.Resource.Styleable.actionbar_background = ReceiptRewards.Droid2.Resource.Styleable.actionbar_background;
			LegacyBar.Library.Resource.Styleable.actionbar_background_item = ReceiptRewards.Droid2.Resource.Styleable.actionbar_background_item;
			LegacyBar.Library.Resource.Styleable.actionbar_is_bottom = ReceiptRewards.Droid2.Resource.Styleable.actionbar_is_bottom;
			LegacyBar.Library.Resource.Styleable.actionbar_light_icons = ReceiptRewards.Droid2.Resource.Styleable.actionbar_light_icons;
			LegacyBar.Library.Resource.Styleable.actionbar_separator = ReceiptRewards.Droid2.Resource.Styleable.actionbar_separator;
			LegacyBar.Library.Resource.Styleable.actionbar_theme = ReceiptRewards.Droid2.Resource.Styleable.actionbar_theme;
			LegacyBar.Library.Resource.Styleable.actionbar_title = ReceiptRewards.Droid2.Resource.Styleable.actionbar_title;
			LegacyBar.Library.Resource.Styleable.actionbar_title_color = ReceiptRewards.Droid2.Resource.Styleable.actionbar_title_color;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090001
			public const int LinkArray = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int PlanetsArray = 2131296256;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int background = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int background_item = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int is_bottom = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int light_icons = 2130771975;
			
			// aapt resource value: 0x7f010002
			public const int separator = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int theme = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int title = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int title_color = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050039
			public const int Red = 2131034169;
			
			// aapt resource value: 0x7f050023
			public const int actionbar_accentcolor_black = 2131034147;
			
			// aapt resource value: 0x7f05002b
			public const int actionbar_accentcolor_blue = 2131034155;
			
			// aapt resource value: 0x7f05001b
			public const int actionbar_accentcolor_darkgray = 2131034139;
			
			// aapt resource value: 0x7f050013
			public const int actionbar_accentcolor_lightgray = 2131034131;
			
			// aapt resource value: 0x7f050003
			public const int actionbar_background_end = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int actionbar_background_end_alt = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int actionbar_background_item_pressed_end = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int actionbar_background_item_pressed_end_alt = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int actionbar_background_item_pressed_start = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int actionbar_background_item_pressed_start_alt = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int actionbar_background_start = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int actionbar_background_start_alt = 2131034120;
			
			// aapt resource value: 0x7f050022
			public const int actionbar_maincolor_black = 2131034146;
			
			// aapt resource value: 0x7f05002a
			public const int actionbar_maincolor_blue = 2131034154;
			
			// aapt resource value: 0x7f05001a
			public const int actionbar_maincolor_darkgray = 2131034138;
			
			// aapt resource value: 0x7f050012
			public const int actionbar_maincolor_lightgray = 2131034130;
			
			// aapt resource value: 0x7f050024
			public const int actionbar_pressedcolor_black = 2131034148;
			
			// aapt resource value: 0x7f05002c
			public const int actionbar_pressedcolor_blue = 2131034156;
			
			// aapt resource value: 0x7f05001c
			public const int actionbar_pressedcolor_darkgray = 2131034140;
			
			// aapt resource value: 0x7f050014
			public const int actionbar_pressedcolor_lightgray = 2131034132;
			
			// aapt resource value: 0x7f050000
			public const int actionbar_separator = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int actionbar_separator_alt = 2131034118;
			
			// aapt resource value: 0x7f050026
			public const int actionbar_separator_black = 2131034150;
			
			// aapt resource value: 0x7f05002e
			public const int actionbar_separator_blue = 2131034158;
			
			// aapt resource value: 0x7f05001e
			public const int actionbar_separator_darkgray = 2131034142;
			
			// aapt resource value: 0x7f050016
			public const int actionbar_separator_lightgray = 2131034134;
			
			// aapt resource value: 0x7f050001
			public const int actionbar_title = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int actionbar_title_alt = 2131034119;
			
			// aapt resource value: 0x7f050025
			public const int actionbar_title_black = 2131034149;
			
			// aapt resource value: 0x7f05002d
			public const int actionbar_title_blue = 2131034157;
			
			// aapt resource value: 0x7f05001d
			public const int actionbar_title_darkgray = 2131034141;
			
			// aapt resource value: 0x7f050015
			public const int actionbar_title_lightgray = 2131034133;
			
			// aapt resource value: 0x7f050033
			public const int black = 2131034163;
			
			// aapt resource value: 0x7f050036
			public const int blue = 2131034166;
			
			// aapt resource value: 0x7f05000f
			public const int bottomactionbar_background_end = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int bottomactionbar_background_item_pressed_end = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int bottomactionbar_background_item_pressed_start = 2131034129;
			
			// aapt resource value: 0x7f05000e
			public const int bottomactionbar_background_start = 2131034126;
			
			// aapt resource value: 0x7f050027
			public const int bottomactionbar_maincolor_black = 2131034151;
			
			// aapt resource value: 0x7f05002f
			public const int bottomactionbar_maincolor_blue = 2131034159;
			
			// aapt resource value: 0x7f05001f
			public const int bottomactionbar_maincolor_darkgray = 2131034143;
			
			// aapt resource value: 0x7f050017
			public const int bottomactionbar_maincolor_lightgray = 2131034135;
			
			// aapt resource value: 0x7f050028
			public const int bottomactionbar_pressedcolor_black = 2131034152;
			
			// aapt resource value: 0x7f050030
			public const int bottomactionbar_pressedcolor_blue = 2131034160;
			
			// aapt resource value: 0x7f050020
			public const int bottomactionbar_pressedcolor_darkgray = 2131034144;
			
			// aapt resource value: 0x7f050018
			public const int bottomactionbar_pressedcolor_lightgray = 2131034136;
			
			// aapt resource value: 0x7f05000c
			public const int bottomactionbar_separator = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int bottomactionbar_title = 2131034125;
			
			// aapt resource value: 0x7f050034
			public const int green = 2131034164;
			
			// aapt resource value: 0x7f050037
			public const int grey = 2131034167;
			
			// aapt resource value: 0x7f050029
			public const int pager_black = 2131034153;
			
			// aapt resource value: 0x7f050031
			public const int pager_blue = 2131034161;
			
			// aapt resource value: 0x7f050021
			public const int pager_darkgray = 2131034145;
			
			// aapt resource value: 0x7f050019
			public const int pager_lightgray = 2131034137;
			
			// aapt resource value: 0x7f050035
			public const int red = 2131034165;
			
			// aapt resource value: 0x7f050032
			public const int white = 2131034162;
			
			// aapt resource value: 0x7f050038
			public const int yellow = 2131034168;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int actionbar_accentheight = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int actionbar_height = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int actionbar_home_item_width = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int actionbar_item_height = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int actionbar_item_height_over = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int actionbar_item_height_overflow = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int actionbar_item_width = 2131099652;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_other = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int action_search = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int actionbar_back_indicator = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int actionbar_back_indicator_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int actionbar_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int actionbar_background_alt = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int actionbar_background_black = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int actionbar_background_blue = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int actionbar_background_darkgray = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int actionbar_background_lightgray = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int actionbar_btn = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int actionbar_btn_alt = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int actionbar_btn_black = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int actionbar_btn_blue = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int actionbar_btn_darkgray = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int actionbar_btn_lightgray = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int actionbar_btn_normal = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int actionbar_btn_normal_alt = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int actionbar_btn_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int actionbar_btn_pressed_alt = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bottomactionbar_background = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bottomactionbar_background_black = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int bottomactionbar_background_blue = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int bottomactionbar_background_darkgray = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int bottomactionbar_background_lightgray = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int bottomactionbar_btn = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int bottomactionbar_btn_black = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int bottomactionbar_btn_blue = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int bottomactionbar_btn_darkgray = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int bottomactionbar_btn_lightgray = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int bottomactionbar_btn_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int bottomactionbar_btn_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int drawer_shadow_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int drawer_shadow_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int dropdown_btn_holo_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int dropdown_btn_holo_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int dropdown_disabled_holo_dark = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int dropdown_disabled_holo_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int dropdown_focused_holo_dark = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int dropdown_focused_holo_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int dropdown_normal_holo_dark = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int dropdown_normal_holo_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int dropdown_pressed_holo_dark = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int dropdown_pressed_holo_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_action_overflow = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_action_overflow_dark = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_drawer_dark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_drawer_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int icon = 2130837552;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040017
			public const int action_websearch = 2130968599;
			
			// aapt resource value: 0x7f040013
			public const int actionbar = 2130968595;
			
			// aapt resource value: 0x7f04000b
			public const int actionbar_actions = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int actionbar_home = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int actionbar_home_bg = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int actionbar_home_btn = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int actionbar_home_is_back = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int actionbar_home_logo = 2130968583;
			
			// aapt resource value: 0x7f040010
			public const int actionbar_item = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int actionbar_progress = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int actionbar_spinner = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int actionbar_title = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int actionbar_title_layout = 2130968588;
			
			// aapt resource value: 0x7f040000
			public const int custom = 2130968576;
			
			// aapt resource value: 0x7f040012
			public const int drawer_layout = 2130968594;
			
			// aapt resource value: 0x7f040003
			public const int holo_black = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int holo_blue = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int holo_gray = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int holo_light = 2130968577;
			
			// aapt resource value: 0x7f040011
			public const int image = 2130968593;
			
			// aapt resource value: 0x7f040015
			public const int left_drawer = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int overflow_spinner = 2130968598;
			
			// aapt resource value: 0x7f040014
			public const int pager = 2130968596;
			
			// aapt resource value: 0x7f040005
			public const int screen = 2130968581;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actionbar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int actionbar_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int blankspinner = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DrawerListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FragmentPlanet = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int FragmentTabsPager = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int overflowactionbar_item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int spinneritem = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int main = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int DrawerClose = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int DrawerOpen = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int action_slidingpane = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int action_websearch = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int actionbar_activity_not_found = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int app_not_available = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int fragment_tabs_pager = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int sliding_pane_layout_summary = 2131165192;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int actionbar = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int actionbarhomeitem = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int actionbarhomelogo = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int actionbaritem = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int actionbarprogressbar = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int clearbutton = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] actionbar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 3
			public const int actionbar_background = 3;
			
			// aapt resource value: 4
			public const int actionbar_background_item = 4;
			
			// aapt resource value: 6
			public const int actionbar_is_bottom = 6;
			
			// aapt resource value: 7
			public const int actionbar_light_icons = 7;
			
			// aapt resource value: 2
			public const int actionbar_separator = 2;
			
			// aapt resource value: 5
			public const int actionbar_theme = 5;
			
			// aapt resource value: 0
			public const int actionbar_title = 0;
			
			// aapt resource value: 1
			public const int actionbar_title_color = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
